config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'comics#index'
  resources :comics, only: [:index] do
    post 'favorite', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @character = params[:character] if params[:character].present?
    @page = params[:page].to_i || 0
    @comics = if params[:character]
                character_id = MarvelService.new.character_id(params[:character])
                character_id ? MarvelService.new.character_comics(character_id, @page) : { 'data' => { 'results' => [] } }
              else
                MarvelService.new.comics(@page)
              end

    Rails.logger.debug "Comics response: #{@comics.inspect}"
    Rails.logger.info "Current favorites: #{session[:favorites].inspect}"
  end

  def favorite
    comic_id = params[:id]
    session[:favorites] ||= []

    if session[:favorites].include?(comic_id.to_i)
      session[:favorites].delete(comic_id.to_i)
      icon = 'heart_off.png'
    else
      session[:favorites] << comic_id.to_i
      icon = 'heart_on.png'
    end

    respond_to do |format|
      format.html { redirect_to comics_path }
      format.json { render json: { icon: icon } }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/comics/_comic.html.erb
<% favorite_icon = session[:favorites]&.include?(comic["id"].to_i) ? 'heart_on.png' : 'heart_off.png' %>

<div class="comic">
  <div class="comic-image <%= 'favorite' if session[:favorites]&.include?(comic["id"].to_i) %>">
    <img src="<%= comic["thumbnail"]["path"] %>.jpg" alt="<%= comic["title"] %> Cover" />
    <div class="favorite-button" data-comic-id="<%= comic['id'] %>">
      <%= link_to image_tag(favorite_icon, alt: 'Favorite', class: 'favorite-icon', id: "favorite-icon-#{comic['id']}"), favorite_comic_path(comic["id"]), method: :post, remote: true, class: 'favorite-btn' %>
    </div>
    <div class="comic-title"><%= comic["title"] %></div>
  </div>
</div>

app/views/comics/_footer.html.erb
<div class="pagination">
  <%= link_to 'PREVIOUS PAGE', comics_path(page: @page - 1, character: @character), class: "pagination-link previous #{'disabled' if @page <= 0}" %>
  <%= link_to 'NEXT PAGE', comics_path(page: @page + 1, character: @character), class: 'pagination-link next' %>
</div>

app/views/comics/_header.html.erb
<header>
  <%= link_to image_tag('marvel_logo.png', alt: 'Marvel Logo', style: 'max-width: 300px;'), root_path %>

  <div style="margin: 20px 0;">
    <%= form_with url: comics_path, method: :get, local: true do |form| %>
      <div>
        <%= form.text_field :character, value: params[:character],placeholder: 'Type a character name...', style: 'width: 300px;' %>
      </div>
    <% end %>
  </div>
</header>

app/views/comics/index.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Marvel Comic Books</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'comics', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'header' %>

  <div class="comic-container">
    <% if @comics && @comics["data"] && @comics["data"]["results"] %>
      <% @comics["data"]["results"].each do |comic| %>
        <%= render 'comic', comic: comic %>
      <% end %>
    <% else %>
      <p>No comics found or API error: <%= @comics["message"] %>.</p>
    <% end %>
  </div>

  <%= render 'footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarvelComicBooks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>